name: github action  CI for nodejs

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 
      uses: actions/setup-node@v3.9.1
      with:
        node-version: 22

    - name: Install dependencies
      working-directory: docker-conatiner-actions/NODEJS-CI
      run: npm install

    - name: Run build
      working-directory: docker-conatiner-actions/NODEJS-CI
      run: npm run build

    - name: Run tests
      working-directory: docker-conatiner-actions/NODEJS-CI
      run: npm test
